### ISSUE TITLE
Brickset doesn't properly urlencode the urls, causing the script to throw errors when it attempts to pass the urls to Invoke-WebRequest.

### ISSUE THREAD

**Issue by wertercatt** [knelmes/Lego-Build-Instructions-Downloader#3]
For example, the index.csv from brickset provides this link: https://www.lego.com/cdn/product-assets/product.bi.additional.extra.pdf/8110_X_8110 Snow Plow #1.pdf

The proper encoded link is: https://www.lego.com/cdn/product-assets/product.bi.additional.extra.pdf/8110_X_8110%20Snow%20Plow%20%231.pdf

This is almost surely an issue on their part, but it is rather annoying to manually fix the URLs in the index.

**Comment by wertercatt** [comment]
![image](https://user-images.githubusercontent.com/7116755/117523048-5746df00-af7c-11eb-88f6-3b07e253c1e4.png)
I also reported the bug to brickset, since it's more their issue than yours. Hopefully they can sort things out on their end.

**Comment by downloadtheworld** [comment]
Hello

I've added some url encoding but the options in powershell are are bit weird because EscapeUriString has a load of reserved characters, including + and #, which is a bit useless, and EscapeDataString converts the :// in http://, breaking the url, so I've had to use EscapeDataString and then put the :// back in. 

Anyway, point is, should work now but because of all that I might have introduced new bugs. Also, if the csv gets the URLs encoded properly, this will break and lines 9 and 10 will need removing.
